<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>59f37283-413e-445c-8282-a5d6543a6c33</elementGuidId>
    <imagePath></imagePath>
    <name>button_seriesB</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/div[1]/div[1]/form[1]/div[1]/div[1]/div[1]/div[1]/div[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="dropdown\ bootstrap-select\ js-dynamic-table-categories-filter\ h-100\ px-0"] &gt; .btn</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Series B') and equals(@type,'button') and equals(@text,'Series B')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>button[title=\"Series B\"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Series B</value>
        <webElementGuid>9e9bea71-ce07-4af2-9121-dee5d7ff9f45</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Series B</value>
        <webElementGuid>9e9bea71-ce07-4af2-9121-dee5d7ff9f45</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>9e9bea71-ce07-4af2-9121-dee5d7ff9f45</webElementGuid>
    </webElementProperties>
</WebElementEntity>