<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>ADO Test suite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>db4a1725-19ba-4d35-a1fb-a0092dc58f20</testSuiteGuid>
   <testCaseLink>
      <guid>529b695f-8f31-4e51-8541-9033babbd9af</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Common Test Cases/Login Level Arrow for the Test Case All references to this Test Case are also updated</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>19fe967b-1564-4705-aff2-848d45b84489</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75fa3d79-7e92-4d55-b359-f7c9493ea288</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>95910cd3-3563-467a-9434-6c5227fd8436</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Common Test Cases/Login Azure 02</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>00c0ff58-4789-4533-a258-ff2e8923306f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b2a4188e-7b54-4245-ac63-74fd1f499b58</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9f612947-81db-4913-9d9f-6c0027b12266</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Common Test Cases/Login Azure 03</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5f6a4097-d85b-4d37-a0ee-b6b77d6f0702</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1969207c-12cc-4f59-9e8b-03e929698628</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
