<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_Verify test case TC3, TC4</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>d1d094b8-2e30-4452-8bac-8d2a4c27099f</testSuiteGuid>
   <testCaseLink>
      <guid>4378c824-09e0-4c18-9536-5c596525c4e2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Main Test Cases/TC3_Verify Login Dialog Origin Page</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e1b056f9-45e1-4ebc-be6a-a9984e648970</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d8f2669-3197-43d3-8476-0b15fb374157</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40a272ea-3b0e-4729-a243-8647f1b33887</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>24fa8624-5910-448e-9303-e99b483b616e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Main Test Cases/TC4_Verify Make Appointment Button - Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>06c231c7-0cee-4ce7-a102-a48caf9e7df3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac9fbb96-e2f8-422b-b4c3-2807cfabdd04</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>67c570fc-0d7e-4e74-8bcc-199b7a20bd99</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>eee16454-6e03-4372-850e-c3a60fe7d73e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Main Test Cases/TC7_Verify user can add TS</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>adeb4890-f84d-49a6-928d-143feb4a0320</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af797889-f11e-47ed-ab37-c34f37fd56f1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c9fc8a00-c7c1-4c8d-b0a7-9fed6648af8a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7902d5dd-12c9-42c4-b6be-01a484857128</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Main Test Cases/TC1_Verify Successful Login_With TestOps Vision</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14d98e7b-4ac8-4e28-8ce7-394001d188f0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a97344e7-5f9c-4936-92a2-d85e5463f3c9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f511468b-f7ec-4a6b-a846-099bea38eeb3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3eaefa3e-13e0-4136-92bd-4eab01d87a29</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Main Test Cases/TC2_Verify Successful Appointment_With TestOps Vision</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e2dec500-1cc2-4ada-8aac-e73448eec660</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ea6e44e-ce39-405d-9d1d-3ab35a178d43</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e05bec37-8dfc-4de2-978a-965e4f5538dd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>58c15445-d45d-46e6-ac70-c7adbbd2cc87</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eacdca82-eacc-4d25-b197-4c041b388673</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>531ffc7f-7d0a-4026-ab99-e2e68882bc87</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb415e4d-2c48-4c2d-b042-07a4d492a48b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>77ea1a9c-6b15-4813-9be5-4a13ffa4d742</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Main Test Cases/TC8_Verify user can delete test case</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10a50878-931e-4944-abbf-17253e6a5b52</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a331b7d-88db-4c36-ab10-3fc6838ba214</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4f5551ac-02bd-483b-91c2-f560e5ebe859</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8608dfa3-63c8-4b23-901a-8d41269fec12</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Main Test Cases/TC5_Verify user can create execution</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d5105c5-a79f-4bbf-ada5-2e619f92524f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>84c530e5-968e-43a7-8e4b-ac573bcb17c1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>967ec302-f8d8-46ee-9635-ae7ee0fe153f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1ee557a1-9836-49c6-bd0d-43e3a8720886</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Main Test Cases/TC6_Verify user can edit execution</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>691b0f3a-791d-4ad8-a2b0-9a9fa670d231</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f68f175e-7dab-4ae8-983b-45b3d5117643</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>92ed9bd0-0520-4597-93bf-bc1e284893b9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>091d0d49-0416-4256-83d6-1c85f021a1b7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac4065c5-4567-4d49-be03-54f25f9076a4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>619a567a-5e77-4c19-b346-4246188b23ba</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18de96f9-7202-4194-97f0-12cb7c44b292</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>57e39be6-164b-440d-a9e5-33744635c9ab</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Main Test Cases/TC3_Verify Login Dialog Origin Page</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e1b056f9-45e1-4ebc-be6a-a9984e648970</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d8f2669-3197-43d3-8476-0b15fb374157</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40a272ea-3b0e-4729-a243-8647f1b33887</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>42389a8e-05b8-4470-b442-9ea4dcceb7d5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Main Test Cases/TC4_Verify Make Appointment Button - Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>06c231c7-0cee-4ce7-a102-a48caf9e7df3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac9fbb96-e2f8-422b-b4c3-2807cfabdd04</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>67c570fc-0d7e-4e74-8bcc-199b7a20bd99</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
