<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>5c59c897-0b10-4610-8e6f-72aaf6c3b4da</elementGuidId>
    <imagePath></imagePath>
    <name>link_fundFacts</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/header[1]/div[2]/div[1]/div[1]/div[1]/ul[1]/li[5]/div[1]/div[1]/ul[1]/li[1]/a[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>body:nth-of-type(1) &gt; header:nth-of-type(1) &gt; div:nth-of-type(2) &gt; div:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(1) &gt; ul:nth-of-type(1) &gt; li:nth-of-type(5) &gt; div:nth-of-type(1) &gt; div:nth-of-type(1) &gt; ul:nth-of-type(1) &gt; li:nth-of-type(1) &gt; a:nth-of-type(2)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'https://www.fidelity.ca/en/fundfacts/') and equals(@text,'Fund Facts &amp; ETF Facts
            
            Search for Fund Fact documents for all Fidelity mutual funds or ETFs.')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>li:nth-child(5) &gt; .fd-megamenu--desktop__content &gt; .fd-megamenu--desktop__content-container &gt; .fd-megamenu--desktop__submenu &gt; .fd-megamenu--desktop__subjects &gt; a:nth-child(2)</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>https://www.fidelity.ca/en/fundfacts/</value>
        <webElementGuid>9e9bea71-ce07-4af2-9121-dee5d7ff9f45</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Fund Facts &amp; ETF Facts
        
        Search for Fund Fact documents for all Fidelity mutual funds or ETFs.</value>
        <webElementGuid>9e9bea71-ce07-4af2-9121-dee5d7ff9f45</webElementGuid>
    </webElementProperties>
</WebElementEntity>