<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>fa45ac42-9e55-48b0-aebd-b8a3ca6e72a5</elementGuidId>
    <imagePath></imagePath>
    <name>link_sustainableInvestments</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/header[1]/div[2]/div[1]/div[1]/div[1]/ul[1]/li[1]/div[1]/div[1]/ul[1]/li[1]/a[5]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>li:nth-of-type(1) .container a:nth-of-type(5)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'{{url}}') and equals(@text,'Sustainable investments
            
            Browse our selection of sustainable investment mutual funds and ETFs available to Canadian investors.')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>.fd-megamenu--desktop__subjects &gt; a:nth-child(5) &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>{{url}}</value>
        <webElementGuid>9e9bea71-ce07-4af2-9121-dee5d7ff9f45</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Sustainable investments
        
        Browse our selection of sustainable investment mutual funds and ETFs available to Canadian investors.</value>
        <webElementGuid>9e9bea71-ce07-4af2-9121-dee5d7ff9f45</webElementGuid>
    </webElementProperties>
</WebElementEntity>