<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>9b0f5cdc-0d30-4b3f-827c-e475947b47e1</elementGuidId>
    <imagePath></imagePath>
    <name>link_aDscLlLl2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/div[1]/div[1]/div[1]/div[1]/article[1]/div[1]/div[2]/form[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[3]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[id="bs-select-1-2"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'bs-select-1-2') and equals(@text,'A (DSC,LL,LL2)')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#bs-select-1-2</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>bs-select-1-2</value>
        <webElementGuid>9e9bea71-ce07-4af2-9121-dee5d7ff9f45</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>A (DSC,LL,LL2)</value>
        <webElementGuid>9e9bea71-ce07-4af2-9121-dee5d7ff9f45</webElementGuid>
    </webElementProperties>
</WebElementEntity>