<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>0138243a-c7f4-4133-8004-f25e8dc5d1e6</elementGuidId>
    <imagePath></imagePath>
    <name>link_fidelityAdvancedUsequityFund</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/div[1]/div[1]/div[1]/div[1]/article[1]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr[8]/td[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>tr:nth-of-type(8) &gt; .fund-name &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'{{url}}')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>a &gt;&gt; internal:text=\"Fidelity Advanced U.S. Equity Fund - US$\"s &gt;&gt; nth=1</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>{{url}}</value>
        <webElementGuid>9e9bea71-ce07-4af2-9121-dee5d7ff9f45</webElementGuid>
    </webElementProperties>
</WebElementEntity>