<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ab24214c-dc9e-48f1-bd19-05b4a3daa23f</elementGuidId>
    <imagePath></imagePath>
    <name>link_discoverSustainableInvesting</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/div[1]/div[9]/div[1]/div[2]/div[3]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="fd-common-btn\ fd-primary-btn"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Discover the approaches to sustainable investing') and equals(@href,'{{url}}') and equals(@text,'Discover the approaches to sustainable investing')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>a[title=\"Discover the approaches to sustainable investing\"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>{{url}}</value>
        <webElementGuid>9e9bea71-ce07-4af2-9121-dee5d7ff9f45</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Discover the approaches to sustainable investing</value>
        <webElementGuid>9e9bea71-ce07-4af2-9121-dee5d7ff9f45</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Discover the approaches to sustainable investing</value>
        <webElementGuid>9e9bea71-ce07-4af2-9121-dee5d7ff9f45</webElementGuid>
    </webElementProperties>
</WebElementEntity>