name: Trigger auto sync

on:
  workflow_dispatch:
  push:
    branches:
      - qa

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Debug files
        run: |
          pwd
          ls -R

      - name: Upload report to TestOps
        run: |
          java -jar ./Github-HealthCheck/Drivers/katalon-report-uploader-0.0.11.jar \
            --projectId=15601 \
            --path="${{ github.workspace }}/reports" \
            --password="${{ secrets.AUTOMATION_KATALON_KEY }}" \
            --type=katalon \
            --server=https://nhily-true-enterprise-17132-g3-apr.qa.katalon.com
